### ISSUE TITLE
Error while execute

### ISSUE THREAD

**Issue by Hvkvn** [anki/cozmo-csharp-sdk#7]
I get the following error, when i execute the c# project.

System.Exception: "CladMismatchEngineToGame - Engine's hash (85-D5-22-11-FD-EB-05-FD-80-7A-6E-8B-10-0C-CB-78) != UI's (E4-85-DF-06-86-B7-D9-55-0C-9C-B4-CB-96-E2-D6-36)"

Could it be that the version of the csharp-sdk is not up to date?

**Comment by ankiNicolas** [comment]
Good catch, you are correct.
